# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Hungry Birds
subtitle: Les aventures d’un couple d’oiseaux voyageurs qui veut dévorer le monde
description: Le blog de Val et Pierre, lors de notre voyage autour du monde. Canada, USA, Japon et Taïwan sont au programme.
author: Pierre
language: fr
timezone: Europe/Zurich

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://hungrybirds.toile-libre.org/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 1
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: LL
time_format: HH:mm

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

## Plugins: https://hexo.io/plugins/
image_server_url: '/images/'

### SCSS
node_sass:
  debug: false
  outputStyle: compressed
  precision: 5
  sourceComments: false

### Autoprefixer
autoprefixer:
  exclude:
    - '*.min.css'
  browsers:
    - 'last 2 versions'

### Sitemap
sitemap:
  path: sitemap.xml

### HTML Minifier
html_minifier:
  exclude:
  removeComments: true

### JS Uglify
uglify:
  mangle: true
  output:
  compress:
  exclude:
    - '*.min.js'

## Themes: https://hexo.io/themes/
theme: hungrybirds

feed:
  type: atom
  path: atom.xml
  limit: 10

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: ftpsync
  host: ftp.toile-libre.org
  user: pfritsch
  pass: r77o,;mMhW$AJc9H
  remote: /hungrybirds/hungrybirds.toile-libre.org-web/htdocs
  port: 21
  ignore: /_WIP
  connections: 1
  verbose: false
