# Header
menu:
  Blog: /
  #Archives: /archives
  Itinéraire: /archives
  À Propos: /about

rss: /atom.xml

# Disqus Comments Shortname
disqus_shortname: hungry-birds

# Content
excerpt_link: Read More
fancybox: false

widgets:
- map
# - category
# - tag
# - tagcloud
# - archive
# - recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
favicon: /images/favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
